---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

# - name: 'Configure WIFI'
# copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: setup apt
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-apt

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ffmpeg
    - python-configobj
    - python-dateutil
    - python-pycurl
    - python-flask
    - python-sqlalchemy
    - python-sdnotify
    - git

- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: "Setup /etc/hosts"
  template: >
          src=hosts.j2
          dest=/etc/hosts
  tags: hosts

- name: Change the hostname
  hostname:
    name: "{{new_hostname}}"
  tags: hosts

- name: change password
  user:
    name: pi 
    update_password: always
    password: "{{ 'changeme' | password_hash('sha512') }}"
  tags:
    - changepwd


# - name: 'Reboot'
#   shell: sleep 2 && reboot
#   async: 1
#   poll: 0
#   ignore_errors: true
#
# - name: "Wait for Raspberry PI to come back"
#   local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
#   become: false
